apiVersion: v1
kind: Service
metadata:
  name: go-simple
spec:
  type: NodePort
  selector:
    app: go-simple
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 9000
